version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: velora-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: velora-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
