server.port=8081
spring.application.name=shipping-service
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/shipping_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
springdoc.swagger-ui.path=/swagger-ui.html
app.jwt.secret=${JWT_SECRET:velora-super-secret-key-for-jwt-hs256-minimum-32-bytes}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
app.kafka.topics.order-created=velora.order.topic
app.kafka.topics.payment-success=velora.payment.success.topic
app.kafka.topics.payment-failed=velora.payment.failed.topic
app.kafka.topics.shipment-created=velora.shipment.created.topic
app.kafka.topics.payment-success-dlq=velora.payment.success.topic.DLQ
