server:
  port: 8081

spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:mysql://localhost:3306/shipping_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: OFF
